
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame


class PageProcessPlay(Frame):

    # user data

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame_process_play")

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.controller = controller

        # set user data

        # set window size
        width = 1024
        height = 600

        screenwidth = controller.winfo_screenwidth()
        screenheight = controller.winfo_screenheight()
        alignstr = '%dx%d+%d+%d' % (width, height, (screenwidth - width) / 2, (screenheight - height) / 2)
        controller.geometry(alignstr)
        controller.resizable(width=False, height=False)


        # gradient background
        #self.canvas = GradientFrame(self, colors = ("white", "#F0F0F0"), width = 1024, height = 600)
        #self.canvas.config(direction = self.canvas.top2bottom)

        
        # flat background
        self.canvas = Canvas(
            self,
            bg = "#FFFFFF",
            height = 600,
            width = 1024,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.grid(row = 0, column = 0, sticky = "nsew")

        # add elements here
        self.canvas.create_rectangle(
            117.0,
            0.0,
            901.0,
            600.0,
            fill="#F9F9F9",
            outline="")

        self.button_image_process_on = PhotoImage(
            file=self.relative_to_assets("button_process_on.png"))
        self.button_process = Button(self,
            image=self.button_image_process_on,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_process.place(
            x=0.0,
            y=103.0,
            width=120.0,
            height=103.0
        )

        self.button_image_home_off = PhotoImage(
            file=self.relative_to_assets("button_home_off.png"))
        self.button_home = Button(self,
            image=self.button_image_home_off,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        self.button_home.place(
            x=0.0,
            y=0.0,
            width=120.0,
            height=103.0
        )

        self.button_image_result_off = PhotoImage(
            file=self.relative_to_assets("button_result_off.png"))
        self.button_result = Button(
            image=self.button_image_result_off,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        self.button_result.place(
            x=0.0,
            y=206.0,
            width=120.0,
            height=103.0
        )

        self.button_image_setting_off = PhotoImage(
            file=self.relative_to_assets("button_setting_off.png"))
        self.button_setting = Button(self,
            image=self.button_image_setting_off,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        self.button_setting.place(
            x=0.0,
            y=497.0,
            width=120.0,
            height=103.0
        )

        self.canvas.create_text(
            148.0,
            16.0, #24.0,
            anchor="nw",
            text="PROCESS",
            fill="#569FCB",
            font=("Noto Sans", 32 * -1, "bold")
        )

        self.canvas.create_rectangle(
            904.0,
            0.0,
            1024.0,
            600.0,
            fill="#E6EFF4",
            outline="")

        self.button_image_stop_off = PhotoImage(
            file=self.relative_to_assets("button_stop_off.png"))
        self.button_stop = Button(self,
            image=self.button_image_stop_off,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_5 clicked"),
            relief="flat"
        )
        self.button_stop.place(
            x=938.0,
            y=233.0,
            width=52.0,
            height=52.0
        )

        self.button_image_edit_off = PhotoImage(
            file=self.relative_to_assets("button_edit_off.png"))
        self.button_edit = Button(self,
            image=self.button_image_edit_off,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        self.button_edit.place(
            x=938.0,
            y=27.0,
            width=52.0,
            height=52.0
        )

        self.button_image_play_on = PhotoImage(
            file=self.relative_to_assets("button_play_on.png"))
        self.button_play = Button(self,
            image=self.button_image_play_on,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_7 clicked"),
            relief="flat"
        )
        self.button_play.place(
            x=903.0,
            y=103.0,
            width=121.0,
            height=104.0
        )

        self.image_state_full = PhotoImage(
            file=self.relative_to_assets("image_state_full.png"))
        self.image_state_1 = self.canvas.create_image(
            278.0,
            262.0,
            image=self.image_state_full
        )

        self.image_state_empty = PhotoImage(
            file=self.relative_to_assets("image_state_empty.png"))
        self.image_state_2 = self.canvas.create_image(
            730.0,
            262.0,
            image=self.image_state_empty
        )

        self.image_state_half = PhotoImage(
            file=self.relative_to_assets("image_state_half.png"))
        self.image_state_3 = self.canvas.create_image(
            504.0,
            262.0,
            image=self.image_state_half
        )

        # title of circles
        self.canvas.create_text(
            277.0,
            133.0, #123.0,
            anchor="center",
            text="PRE-EXTRACT",
            fill="#17171B",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.create_text(
            511.0,
            133.0, #123.0,
            anchor="center",
            text="EXTRACT",
            fill="#17171B",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.create_text(
            729.0,
            133.0, #123.0,
            anchor="center",
            text="QPCR",
            fill="#17171B",
            font=("Noto Sans", 24 * -1)
        )

        # botton of circle
        self.canvas.create_text(
            277.0,
            385.0, #375.0,
            anchor="center",
            text="2 / 2 STEPS",
            fill="#7D8CA7",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.create_text(
            503.0,
            385.0, #375.0,
            anchor="center",
            text="5 / 8 STEPS",
            fill="#7D8CA7",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.create_text(
            729.0,
            385.0, #375.0,
            anchor="center",
            #623.0,
            #367.0, #375.0,
            #anchor="nw",
            text="0 / 40 CYCLES",
            fill="#7D8CA7",
            font=("Noto Sans", 24 * -1)
        )
		
		

        # middle of circle
        self.canvas.create_text(
            277.0,
            255.0, #230.0,
            anchor="center",
            text="0:05",
            fill="#7D8CA7",
            font=("Noto Sans", 46 * -1)
        )

        self.canvas.create_text(
            503.0,
            255.0, #230.0,
            anchor="center",
            text="0:12",
            fill="#7D8CA7",
            font=("Noto Sans", 46 * -1)
        )

        self.canvas.create_text(
            730.0,
            255.0, #230.0,
            anchor="center",
            text="0:25",
            fill="#7D8CA7",
            font=("Noto Sans", 46 * -1)
)

        self.canvas.create_text(
            427.0,
            21.0, #29.0,
            anchor="nw",
            text="Time Remaining?",
            fill="#7D8CA7",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.create_rectangle(
            635.0,
            25.0,
            828.0,
            69.0,
        fill="#FFFFFF",
        outline="black")

        self.canvas.create_text(
            732.0,
            43.0,
            anchor="center",
            text="00:48",
            fill="#17171B",
            font=("Noto Sans", 24 * -1)
        )



if __name__ == "__main__":
    window = Tk()
    window.geometry("1024x600")
    window.configure(bg = "#FFFFFF")

    container = Frame(window, bg="#FFFFFF")
    container.pack(side = "top", fill = "both", expand = True)
    container.grid_rowconfigure(0, weight = 1)
    container.grid_columnconfigure(0, weight = 1)

    window.frames = {}
    frame = PageProcessPlay(container, window)

    window.frames[PageProcessPlay] = frame
    frame.grid(row = 0, column = 0, sticky ="nsew")

    frame.tkraise()
    window.mainloop()
    




