

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
from GradientFrame import GradientFrame                       # add for gradient color background

import page_process_play
import page_process_init

from copic import img_button_cancel_off, img_button_delete_on

class PageCheck(Frame):

    # user data

    #OUTPUT_PATH = Path(__file__).parent
    #ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame_check")

    #def relative_to_assets(self, path: str) -> Path:
    #    return self.ASSETS_PATH / Path(path)

    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.controller = controller

        # set user data

        # set window size
        width = 1024
        height = 600

        screenwidth = controller.winfo_screenwidth()
        screenheight = controller.winfo_screenheight()
        alignstr = '%dx%d+%d+%d' % (width, height, (screenwidth - width) / 2, (screenheight - height) / 2)
        controller.geometry(alignstr)
        controller.resizable(width=False, height=False)

        
        self.canvas = GradientFrame(self, colors = ("white", "#F0F0F0"), width = 1024, height = 600)
        self.canvas.config(direction = self.canvas.top2bottom)
        self.canvas.grid(row = 0, column = 0, sticky = "nsew")

        # add elements here
        
        self.canvas.create_rectangle(
            130.0,
            125.0,
            899.0,
            475.0,
            fill="#FFFFFF",
            outline="#AFAEAE",
        )
        
        
        self.button_image_delete_on = PhotoImage(data=img_button_delete_on)
        self.button_delete = Button(self, image=self.button_image_delete_on, 
                                  borderwidth=0, highlightthickness=0,
                                  command=self.Cmd_btn_stop,
                                  relief="flat")
        self.button_delete.place(
            x=539.0,
            y=355.0,
            width=315.0,
            height=86.0)

        self.button_image_cancel_off = PhotoImage(data=img_button_cancel_off)
        self.button_cancel = Button(self, image=self.button_image_cancel_off, 
                                    borderwidth=0, highlightthickness=0,
                                    command=self.Cmd_btn_cancel,
                                    relief="flat")
        self.button_cancel.place(
            x=177.0,
            y=355.0,
            width=315.0,
            height=86.0)

        self.canvas.create_text(
            515.0,
            244.0,
            anchor="center",
            justify="center",
            text="ARE YOU SURE YOU WANT TO DELETE\nUSER? THIS CANNOT BE UNDONE.",
            fill="#17171B",
            font=("Noto Sans", 32 * -1)
        )

    def Cmd_btn_cancel(self):
        # return to process play
        #self.controller.frames[page_process_play.PageProcessPlay].current_bar.toggle_pause()
        self.controller.frames[page_process_play.PageProcessPlay].step()
        self.controller.show_frame(page_process_play.PageProcessPlay)

    def Cmd_btn_stop(self):
        # stop all hardware
        # return to process inital
        self.controller.frames[page_process_init.PageProcessInit].process_status = -1
        self.controller.frames[page_process_init.PageProcessInit].update_status()
        self.controller.show_frame(page_process_init.PageProcessInit)

if __name__ == "__main__":
    window = Tk()
    window.geometry("1024x600")
    window.configure(bg = "#FFFFFF")

    container = Frame(window, bg="#FFFFFF")
    container.pack(side = "top", fill = "both", expand = True)
    container.grid_rowconfigure(0, weight = 1)
    container.grid_columnconfigure(0, weight = 1)

    window.frames = {}
    frame = PageCheck(container, window)
    frame.grid(row = 0, column = 0, sticky ="nsew")

    window.frames[PageCheck] = frame
    frame.tkraise()

    window.mainloop()
    


