
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
from GradientFrame import GradientFrame                       # add for gradient color background


class PageLogin(Frame):

    # user data

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame_login")

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.controller = controller

        # set user data

        # set window size
        width = 1024
        height = 600

        screenwidth = controller.winfo_screenwidth()
        screenheight = controller.winfo_screenheight()
        alignstr = '%dx%d+%d+%d' % (width, height, (screenwidth - width) / 2, (screenheight - height) / 2)
        controller.geometry(alignstr)
        controller.resizable(width=False, height=False)


        #self.canvas = GradientFrame(parent, colors = ("white", "#F0F0F0"), width = 1024, height = 600)
        #self.canvas.config(direction = self.canvas.top2bottom)
        #self.canvas.grid(row = 0, column = 0, sticky = "nsew")
        #self.canvas.pack()

        self.canvas = Canvas(
            self,
            bg = "#FFFFFF",
            height = 600,
            width = 1024,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)


        self.entry_image_1 = PhotoImage(
            file=self.relative_to_assets("entry_1.png"))

        self.entry_bg_1 = self.canvas.create_image(
            525.0,
            214.0,
            image=self.entry_image_1
        )


        self.entry_1 = Entry(self,
            bd=0,
            bg="#EAEAEA",
            fg="#7E8DA8", # "#17171B",
            highlightthickness=0,
            font = ("Noto Sans", 24 * -1)
        )

        self.entry_1.insert(0, "ENTER USER NAME")

        self.entry_1.place(
            x=217.0,
            y=171.0,
            width=330,
            height=84.0
        )

        self.entry_image_2 = PhotoImage(
            file=self.relative_to_assets("entry_1.png"))
        self.entry_bg_2 = self.canvas.create_image(
            525.0,
            327.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(self,
            bd=0,
            bg="#EAEAEA",
            fg="#7E8DA8", # "#17171B",
            highlightthickness=0,
            font = ("Noto Sans", 24 * -1),
        )

        self.entry_2.insert(0, "ENTER PASSWORD")

        self.entry_2.place(
            x=217.0,
            y=284.0,
            width=330,
            height=84.0
        )


        self.error_password = self.canvas.create_text(
            830.0,
            303.0,
            anchor="ne",
            text="Password Error",
            fill="#F02C95",
            font=("Noto Sans", 24 * -1)
        )


        self.error_username = self.canvas.create_text(
            830.0,
            190.0,
            anchor="ne",
            text="No Account",
            fill="#F02C95",
            font=("Noto Sans", 24 * -1)
        )

        self.canvas.itemconfigure(self.error_password, state="hidden")
        self.canvas.itemconfigure(self.error_username, state="hidden")

        self.image_image_1 = PhotoImage(
            file=self.relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            525.0,
            93.0,
            image=self.image_image_1
        )

        self.button_image_1 = PhotoImage(
            file=self.relative_to_assets("button_1.png"))
        self.button_1 = Button(self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat",
            font=("Noto Sans", 24 * -1),
        )

        self.button_1.place(
            x=185.0,
            y=397.0,
            width=680.0,
            height=86.0
        )



if __name__ == "__main__":
    window = Tk()
    window.geometry("1024x600")
    window.configure(bg = "#FFFFFF")

    container = Frame(window, bg="#FFFFBB")
    container.pack(side = "top", fill = "both", expand = True)
    container.grid_rowconfigure(0, weight = 1)
    container.grid_columnconfigure(0, weight = 1)

    window.frames = {}
    frame = PageLogin(container, window)
    #frame.grid(row = 0, column = 0, sticky ="nsew")

    window.frames[PageLogin] = frame
    frame.tkraise()

    window.mainloop()
    
