
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from GradientFrame import GradientFrame                       # add for gradient color background

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame_login")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFFFFF")


canvas_old = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)



canvas_old.place(x = 0, y = 0)
#canvas.create_rectangle(
#    0.0,
#    0.0,
#    1024.0,
#    600.0,
#    fill="#FFFFFF",
#    outline="")

canvas = GradientFrame(canvas_old, colors = ("white", "#F0F0F0"), width = 1024, height = 600)
canvas.config(direction = canvas.top2bottom)
canvas.pack()


entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    525.0,
    214.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EAEAEA",
    fg="#7E8DA8", # "#17171B",
    highlightthickness=0,
    font = ("Noto Sans", 24 * -1)
)

entry_1.insert(0, "ENTER USER NAME")

entry_1.place(
    x=217.0,
    y=171.0,
#    width=664.0,
    width=330,
    height=84.0
)



entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_2 = canvas.create_image(
    525.0,
    327.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EAEAEA",
    fg="#7E8DA8", # "#17171B",
    highlightthickness=0,
    font = ("Noto Sans", 24 * -1),
)

entry_2.insert(0, "ENTER PASSWORD")

entry_2.place(
    x=217.0,
    y=284.0,
#    width=664.0,
    width=330,
    height=84.0
)

'''
canvas.create_text(
    217.0,
    196.0,
    anchor="nw",
    text="Demo",
    fill="#17171B",
    font=("Noto Sans", 24 * -1)
)
'''

error_password = canvas.create_text(
    830.0,
    303.0,
    anchor="ne",
    text="Password Error",
    fill="#F02C95",
    font=("Noto Sans", 24 * -1)
)


error_username = canvas.create_text(
    830.0,
    190.0,
    anchor="ne",
    text="No Account",
    fill="#F02C95",
    font=("Noto Sans", 24 * -1)
)

canvas.itemconfigure(error_password, state="hidden")
canvas.itemconfigure(error_username, state="hidden")



'''
canvas.create_text(
    217.0,
    316.0,
    anchor="nw",
    text="*********",
    fill="#17171B",
    font=("Noto Sans", 24 * -1)
)
'''

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    525.0,
    93.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    font=("Noto Sans", 24 * -1),
    #fg="#7D8CA7",
    #text="LOGIN"
)
button_1.place(
    x=185.0,
    y=397.0,
    width=680.0,
    height=86.0
)

'''
canvas.create_text(
    343.0,
    422.0,
    anchor="nw",
    text="LOGIN",
    fill="#7D8CA7",
    font=("Noto Sans", 24 * -1)
)
'''
window.resizable(False, False)
window.mainloop()
